### ISSUE TITLE
work in the support for the custom server name

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#373]

**Comment by jparicka** [comment]
also, currently the ajax points to the http://kopi.projectcloudly.com:8001/post .. that definitely needs to be worked out....

**Comment by jparicka** [comment]
I'm getting the 403 error (missing csrf token) at the mo...
handing over to kopik...

**Comment by OndrejKopal** [comment]
Jj, vim o tom, je to jen pripraveny... :)


---------- Původní zpráva ----------

Od: Jan Paricka <notifications@github.com>

Komu: jparicka/cloudly <cloudly@noreply.github.com>

Datum: 8. 7. 2015 12:02:16

Předmět: Re: [cloudly] work in the support for the custom server name (#373)


"

I'm getting the 403 error (missing csrf token) at the mo...

handing over to kopik...

—

Reply to this email directly or view it on GitHub
(https://github.com/jparicka/cloudly/issues/373#issuecomment-119529366). 





"=

**Comment by jparicka** [comment]
:) :)

**Comment by OndrejKopal** [comment]
Pak mi dej vedet, na jakou adresu to mam posilat, ted je tam jen dane '/
post' ;)


---------- Původní zpráva ----------

Od: Jan Paricka <notifications@github.com>

Komu: jparicka/cloudly <cloudly@noreply.github.com>

Datum: 8. 7. 2015 12:07:05

Předmět: Re: [cloudly] work in the support for the custom server name (#373)


"

:) :)

—

Reply to this email directly or view it on GitHub
(https://github.com/jparicka/cloudly/issues/373#issuecomment-119530023). 





"=

**Comment by jparicka** [comment]
Uz jsem to tam updatnul…

pull….    :P


Jan

**Comment by jparicka** [comment]
it's there
