### ISSUE TITLE
introduce the tags on the offline servers

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#478]

**Comment by jparicka** [comment]
thank you!

**Comment by jparicka** [comment]
perhaps we can place them underneath the Server Details?
would that be possible?

![screen shot 2015-08-16 at 08 56 24](https://cloud.githubusercontent.com/assets/870699/9292370/bf019f76-43f4-11e5-8b96-38920867b36c.png)

**Comment by jparicka** [comment]
of course I'm talking these "Tags"..

(example below)
![screen shot 2015-08-16 at 08 57 21](https://cloud.githubusercontent.com/assets/870699/9292373/e69473d8-43f4-11e5-8767-eafd7c2ea5e6.png)

**Comment by OndrejKopal** [comment]
done
