### ISSUE TITLE
swap the "local address" with the "foreign address" on the server detail - "Network connections"

### ISSUE THREAD

**Issue by jparicka** [jparicka/cloudly#489]
or the vice versa, i.e. is this a bug on the backend?  seems like it......

**Comment by jparicka** [comment]
Kopik, can you please investigate?  Thx.

**Comment by jparicka** [comment]
foreign vs local address seems to be swapped?

![screen shot 2015-08-18 at 15 20 29](https://cloud.githubusercontent.com/assets/870699/9330930/ba45d1f4-45bc-11e5-94a8-af7229115382.png)

**Comment by jparicka** [comment]
foreign really is local wtf

**Comment by OndrejKopal** [comment]
closed
