### ISSUE TITLE
HELP! how to install to centos 6.5?

### ISSUE THREAD

**Issue by xsvs** [jparicka/cloudly#747]

**Comment by jparicka** [comment]
why don't you try the agent first?
just navigate to monkeytor.tk and then there is "Add server"..
all you do is that you copy & paste the command it gives you.

**Comment by xsvs** [comment]
i mean installing your app to my centos server :3

**Comment by jparicka** [comment]
I see.  Well, the app isn't quite finished, but essentially if follow the exact steps from the README, all you need to do is instead of "apt-get" type "yum".
A quick hack how to get the OpenTSDB running is here https://github.com/jparicka/cloudly/tree/master/docs

**Comment by jparicka** [comment]
I hope I answered your questions.  If you have any trouble during the installation - hit me up on skype "jparicka" or email jparicka@gmail.com, or here...  I will be glad to help.

**Comment by jparicka** [comment]
It should be easy enough as only a few external modules are required..

**Comment by jparicka** [comment]
I meant here (the quick opentsdb setup instructions) -
https://github.com/jparicka/cloudly/blob/master/docs/opentsdb.md

**Comment by xsvs** [comment]
for what opentsb?
sorry my bad english :(

**Comment by jparicka** [comment]
well, first you need to do the steps from the readme, then you need to go through steps setting up the database.  it's a special type of database called OpenTSDB http://opentsdb.net/ 
utilizing this database allows us to do the super quick down-scaling the graps (i.e. you can click and view 30 days history in a graph).
not sure I'm making sense?
