### ISSUE TITLE
Centos Bugs 

### ISSUE THREAD

**Issue by xsvs** [jparicka/cloudly#748]
Hei baby! :dancer:  you know in remote monitor centos bus not shown network and diskusage :smile:

**Comment by jparicka** [comment]
I know but there isn't much I can do about it right now.
This, just so you know, is just a hobby of mine, which I plan to leave as is.  Can't make it to the product.

**Comment by jparicka** [comment]
Don't take this project seriously - it's a draft, a prototype.

**Comment by jparicka** [comment]
There isn't a real demand for monitoring like this - just so you know..
So it's very much dead for the time being.
But thanks for the thumbs up!

**Comment by xsvs** [comment]
hahaha dont take serious bro...
